#language: go
#go:
#  - "1.10.x"

language: python

addons:  # Add the version of go that we want
  apt:
    sources:
      - sourceline: 'ppa:gophers/archive'
    update: true
    packages: golang-1.10-go

matrix:
  include:
    - os: linux
      env:
        - SUDO=""
          USER_FLAG="--user"
    - os: osx
      env:
        - SUDO="sudo"
          USER_FLAG=""

install:  # These commands are done by Travis when language: go
  - PATH=/usr/lib/go-1.10/bin:${PATH}
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $HOME/gopath/src/github.com/grumpyhome/grumpy
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/grumpyhome/grumpy/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/grumpyhome/grumpy
  - cd $HOME/gopath/src/github.com/grumpyhome/grumpy
  - go env
  - go version
  - go get -t -v ./...
  #- ${PIP_SUDO} pip install --upgrade pip

before_script:
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"  # https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024
# Run gofmt and lint serially to avoid confusing output. Run tests in parallel
# for speed.
  - ${SUDO} python -m pip install pytest pytest-cov coverage ${USER_FLAG} 

script:
  # Install the thing
  - cd grumpy-tools-src
  - ${SUDO} python -m pip install . ${USER_FLAG}
  - which grumpy
  - cd ../grumpy-runtime-src
  - ${SUDO} python -m pip install . ${USER_FLAG}
  # Test the thing
  - cd ../grumpy-tools-src
  - pytest
  - cd ../grumpy-runtime-src
  - make gofmt lint && make -j2 test

# OSX swallows error logs: https://github.com/travis-ci/travis-ci/issues/6018
after_error:
  - echo "== End of test log ==""
